/**
 * Per-component documentation registry — source for MDX pages and public/specs/*.
 * Keep tokens paths as design-token paths (slash form); generate-specs maps to cssVar.
 */
import type { ComponentSpec } from "./types";

export const COMPONENT_SPECS: ComponentSpec[] = [
  {
    id: "button",
    name: "Button",
    storyTitle: "Components/Button",
    overview:
      "Primary interactive control. Hierarchy and colour are independent axes with type-safe allowed pairs. Primary uses bg/neutral/strong — not brand yellow (yellow is for wayfinding/selection).",
    whenToUse: [
      "Trigger actions (submit, confirm, navigate)",
      "Use hierarchy to express emphasis; colour for semantic meaning (destructive, AI, status on secondary/ghost/link)",
      "Prefer link hierarchy for inline textual actions",
    ],
    variants: {
      hierarchy: ["primary", "secondary", "tertiary", "ghost", "link"],
      color: [
        "default",
        "destructive",
        "warning",
        "success",
        "info",
        "ai",
      ],
      size: ["xs", "sm", "md", "lg"],
      icon: ["none", "leading", "trailing", "only"],
      state: ["default", "hover", "active", "focused", "disabled"],
    },
    anatomy: ["Root (button)", "Leading/trailing icon", "Label", "Loading spinner"],
    tokens: {
      role: [
        "bg/neutral/strong",
        "bg/neutral/strong-hover",
        "bg/neutral/strong-active",
        "bg/danger/strong",
        "bg/danger/strong-hover",
        "bg/danger/strong-active",
        "bg/ai/strong",
        "bg/ai/strong-hover",
        "bg/ai/strong-active",
        "bg/surface",
        "bg/disabled",
        "bg/danger/soft",
        "bg/warning/soft",
        "bg/success/soft",
        "bg/info/soft",
        "bg/ai/soft",
        "text/primary",
        "text/on-inverse",
        "text/on-strong",
        "text/disabled",
        "text/link",
        "text/link-hover",
        "text/danger",
        "text/danger-hover",
        "text/warning",
        "text/warning-hover",
        "text/success",
        "text/success-hover",
        "text/info",
        "text/info-hover",
        "text/ai",
        "text/ai-hover",
        "border/focus",
        "border/danger",
        "border/warning",
        "border/success",
        "border/info",
        "border/ai",
      ],
      surface: [
        "surface/border",
        "surface/level-1",
        "surface/level-2",
        "surface/level-3",
      ],
      structure: [
        "control/padding-x",
        "control/padding-y",
        "control/gap",
        "control/icon-padding",
        "control/radius",
        "icon/size",
        "focus/ring-width",
        "focus/ring-offset",
      ],
    },
    props: [
      {
        name: "hierarchy",
        type: "primary | secondary | tertiary | ghost | link",
        default: "primary",
        description: "Visual weight / chrome style.",
      },
      {
        name: "color",
        type: "depends on hierarchy (type-safe)",
        default: "default",
        description: "Semantic colour. Primary only allows default | destructive | ai.",
      },
      {
        name: "size",
        type: "xs | sm | md | lg",
        default: "md",
        description: "Control sizing from Structure.",
      },
      {
        name: "icon",
        type: "none | leading | trailing | only",
        default: "none",
        description: "Icon placement axis.",
      },
      {
        name: "state",
        type: "default | hover | active | focused | disabled",
        default: "default",
        description: "Design-review only — not for production.",
      },
      {
        name: "loading",
        type: "boolean",
        default: "false",
        description: "Shows spinner and sets aria-busy.",
      },
    ],
    accessibility: [
      "Native button semantics; fully keyboard operable",
      "Visible focus ring via focus-visible + border/focus",
      "loading sets aria-busy; disabled via disabled / aria-disabled",
      "icon-only requires aria-label",
      "Respects prefers-reduced-motion on transitions/spinner",
    ],
    do: [
      "Use primary default for the main action on a view",
      "Pair Alert actions as ghost + secondary coloured by role",
      "Leave state at default in product code",
    ],
    dont: [
      "Don't use primary + warning/success/info (blocked at the type level)",
      "Don't put a primary default button inside a coloured Alert",
      "Don't use brand yellow as a primary button fill",
    ],
  },
  {
    id: "input",
    name: "Input",
    storyTitle: "Components/Input",
    overview:
      "Text field with label, helper, and error. Uses Surface field fills so the well stays correct in every context.",
    whenToUse: [
      "Single-line text entry",
      "Pair with Button in form rows",
      "Use errorMessage for validation copy (sets aria-invalid)",
    ],
    variants: {
      size: ["sm", "md", "lg"],
      state: ["default", "hover", "focused", "disabled", "read-only", "error"],
    },
    anatomy: ["Label", "Field", "Prefix/suffix icon", "Clear control", "Helper / error"],
    tokens: {
      role: [
        "text/primary",
        "text/secondary",
        "text/tertiary",
        "text/disabled",
        "text/danger",
        "border/default",
        "border/focus",
        "border/subtle",
        "border/danger",
        "bg/disabled",
        "icon/secondary",
        "icon/tertiary",
        "icon/primary",
      ],
      surface: ["surface/field", "surface/field-hover", "surface/level-1"],
      structure: [
        "control/padding-x",
        "control/padding-y",
        "control/gap",
        "control/radius",
        "control/label-gap",
        "icon/size",
        "focus/ring-width",
        "focus/ring-offset",
      ],
    },
    props: [
      { name: "size", type: "sm | md | lg", default: "md", description: "Field size." },
      { name: "label", type: "string", description: "Visible label." },
      { name: "helperText", type: "string", description: "Supporting copy." },
      { name: "errorMessage", type: "string", description: "Validation message; marks invalid." },
      {
        name: "state",
        type: "default | hover | focused | disabled | read-only | error",
        default: "default",
        description: "Design-review only.",
      },
    ],
    accessibility: [
      "Label associated via htmlFor / id",
      "Helper and error wired through aria-describedby",
      "error / aria-invalid expose invalid state",
      "Clear control has accessible name",
    ],
    do: ["Always provide a visible label for persistent fields", "Prefer errorMessage over colour alone"],
    dont: ["Don't rely on placeholder as the only label", "Don't use state≠default in production"],
  },
  {
    id: "badge",
    name: "Badge",
    storyTitle: "Components/Badge",
    overview: "Compact status or metadata chip. Soft vs strong emphasis; optional dot, count, or icon.",
    whenToUse: ["Status labels", "Counts on tabs/nav", "Non-interactive metadata"],
    variants: {
      role: ["neutral", "info", "success", "warning", "danger", "ai"],
      emphasis: ["soft", "strong"],
      size: ["sm", "md", "lg"],
      state: ["default", "disabled"],
    },
    anatomy: ["Root", "Optional dot", "Optional icon", "Label", "Optional count"],
    tokens: {
      role: [
        "bg/neutral/soft",
        "bg/neutral/strong",
        "bg/info/soft",
        "bg/info/strong",
        "bg/success/soft",
        "bg/success/strong",
        "bg/warning/soft",
        "bg/warning/strong",
        "bg/danger/soft",
        "bg/danger/strong",
        "bg/ai/soft",
        "bg/ai/strong",
        "text/neutral",
        "text/info",
        "text/success",
        "text/warning",
        "text/danger",
        "text/ai",
        "text/on-strong",
        "text/on-strong-warning",
        "text/on-inverse",
        "border/neutral",
        "border/info",
        "border/success",
        "border/warning",
        "border/danger",
        "border/ai",
      ],
      structure: ["chip/padding-x", "chip/padding-y", "chip/gap"],
      component: [
        "badge/radius",
        "badge/dot-size",
        "badge/count-size",
        "badge/count-radius",
      ],
    },
    props: [
      { name: "role", type: "neutral | info | success | warning | danger | ai", default: "neutral", description: "Status colour." },
      { name: "emphasis", type: "soft | strong", default: "soft", description: "Fill weight." },
      { name: "size", type: "sm | md | lg", default: "md", description: "Chip size." },
      { name: "dot", type: "boolean", default: "false", description: "Leading status dot." },
      { name: "count", type: "number | string", description: "Trailing count pill." },
    ],
    accessibility: ["Decorative dots are aria-hidden", "Prefer text content that names the status"],
    do: ["Use soft for inline metadata", "Use strong sparingly for high emphasis"],
    dont: ["Don't make badges the only affordance for a critical action"],
  },
  {
    id: "tag",
    name: "Tag",
    storyTitle: "Components/Tag",
    overview: "Filterable or removable chip for selected values and facets.",
    whenToUse: ["Selected filters", "Removable keywords", "Compact labeled values"],
    variants: {
      size: ["sm", "md", "lg"],
      state: ["default", "hover", "disabled"],
    },
    anatomy: ["Root", "Optional icon", "Label", "Optional remove control"],
    tokens: {
      role: ["text/primary", "text/disabled", "border/subtle", "icon/secondary"],
      surface: ["surface/level-1", "surface/level-2"],
      structure: ["chip/padding-x", "chip/padding-y", "chip/gap", "icon/size"],
      component: ["tag/radius"],
    },
    props: [
      { name: "size", type: "sm | md | lg", default: "md", description: "Chip size." },
      { name: "removable", type: "boolean", default: "false", description: "Shows remove Button." },
      { name: "state", type: "default | hover | disabled", default: "default", description: "Design-review only." },
    ],
    accessibility: ["Remove control is a Button with accessible name", "Disabled tags are not focusable for remove"],
    do: ["Use removable for dismissible selections"],
    dont: ["Don't use Tag for status — use Badge"],
  },
  {
    id: "checkbox",
    name: "Checkbox",
    storyTitle: "Components/Checkbox",
    overview: "Binary or indeterminate multi-select control built on Radix Checkbox.",
    whenToUse: ["Multi-select lists", "Settings toggles that are not immediate on/off (prefer Toggle for that)", "Select-all with indeterminate"],
    variants: {
      size: ["sm", "md", "lg"],
      state: ["default", "unchecked", "checked", "indeterminate", "disabled", "focused", "error"],
    },
    anatomy: ["Root", "Indicator (check / dash)", "Label", "Description"],
    tokens: {
      role: [
        "bg/neutral/strong",
        "bg/disabled",
        "text/on-inverse",
        "text/primary",
        "text/secondary",
        "text/disabled",
        "border/default",
        "border/focus",
        "border/danger",
      ],
      surface: ["surface/field"],
      structure: ["control/label-gap", "focus/ring-width", "focus/ring-offset"],
      component: ["checkbox/size", "checkbox/radius"],
    },
    props: [
      { name: "size", type: "sm | md | lg", default: "md", description: "Box size." },
      { name: "checked", type: "boolean | 'indeterminate'", description: "Controlled checked state." },
      { name: "state", type: "design-review states", default: "default", description: "Design-review only." },
    ],
    accessibility: ["Radix provides checkbox role and keyboard support", "Label clicks toggle the control", "error sets aria-invalid"],
    do: ["Use indeterminate for partial selection"],
    dont: ["Don't use Checkbox for exclusive choices — use Radio"],
  },
  {
    id: "radio",
    name: "Radio",
    storyTitle: "Components/Radio",
    overview: "Exclusive choice within a RadioGroup. Orientation horizontal or vertical.",
    whenToUse: ["Pick one option from a short list", "Form settings with mutually exclusive values"],
    variants: {
      size: ["sm", "md", "lg"],
      orientation: ["vertical", "horizontal"],
      state: ["default", "unselected", "selected", "disabled", "focused"],
    },
    anatomy: ["RadioGroup", "RadioItem", "Indicator dot", "Label"],
    tokens: {
      role: [
        "bg/neutral/strong",
        "text/primary",
        "text/disabled",
        "border/default",
        "border/focus",
      ],
      surface: ["surface/field"],
      structure: ["control/label-gap", "control/content-gap", "focus/ring-width", "focus/ring-offset"],
      component: ["radio/size", "radio/dot-size", "radio/radius"],
    },
    props: [
      { name: "orientation", type: "vertical | horizontal", default: "vertical", description: "Group layout." },
      { name: "size", type: "sm | md | lg", default: "md", description: "Item size." },
      { name: "value", type: "string", description: "Selected value (group)." },
    ],
    accessibility: ["Radiogroup + radio roles from Radix", "Arrow keys move selection within the group"],
    do: ["Provide a group legend/label in the surrounding form"],
    dont: ["Don't use a single Radio without a group"],
  },
  {
    id: "toggle",
    name: "Toggle",
    storyTitle: "Components/Toggle",
    overview: "Immediate on/off switch (Radix Switch). Prefer over Checkbox when the change applies instantly.",
    whenToUse: ["Settings that apply immediately", "Feature flags in UI"],
    variants: {
      size: ["sm", "md", "lg"],
      state: ["default", "off", "on", "disabled", "focused"],
      labelPosition: ["start", "end"],
    },
    anatomy: ["Root (switch)", "Thumb", "Label", "Description"],
    tokens: {
      role: ["bg/neutral/strong", "text/primary", "text/secondary", "text/disabled", "border/focus"],
      structure: ["control/label-gap", "focus/ring-width", "focus/ring-offset"],
      component: [
        "toggle/track-width",
        "toggle/track-height",
        "toggle/knob-size",
        "toggle/track-padding",
        "toggle/radius",
        "toggle/track-off-bg",
        "toggle/track-off-bg-hover",
        "toggle/knob-bg",
      ],
    },
    props: [
      { name: "size", type: "sm | md | lg", default: "md", description: "Switch size." },
      { name: "labelPosition", type: "start | end", default: "end", description: "Label placement." },
      { name: "state", type: "default | off | on | disabled | focused", default: "default", description: "Design-review only." },
    ],
    accessibility: ["switch role from Radix", "Space toggles", "Label is associated"],
    do: ["Use for immediate binary settings"],
    dont: ["Don't use for multi-select — use Checkbox"],
  },
  {
    id: "tabs",
    name: "Tabs",
    storyTitle: "Components/Tabs",
    overview: "Section switching with underline or button (segmented) variants.",
    whenToUse: ["In-page navigation between related views", "Settings panels"],
    variants: {
      variant: ["underline", "button"],
      size: ["sm", "md", "lg"],
      state: ["default", "active", "disabled"],
    },
    anatomy: ["Tabs", "TabsList", "TabsTrigger", "TabsContent", "Optional icon/badge"],
    tokens: {
      role: [
        "text/primary",
        "text/secondary",
        "text/disabled",
        "border/subtle",
        "border/focus",
        "selected/indicator",
        "bg/surface",
      ],
      surface: ["surface/level-1"],
      structure: ["focus/ring-width", "focus/ring-offset", "icon/size"],
      component: [
        "tab/item-spacing",
        "tab/content-gap",
        "tab/indicator-weight",
        "tab/container-radius",
        "tab/container-padding",
        "tab/radius",
      ],
    },
    props: [
      { name: "variant", type: "underline | button", default: "underline", description: "Visual style." },
      { name: "size", type: "sm | md | lg", default: "md", description: "Trigger size." },
    ],
    accessibility: ["tablist / tab / tabpanel roles", "Arrow keys move between tabs"],
    do: ["Keep tab labels short", "Use Badge for counts, not as the only label"],
    dont: ["Don't nest interactive tabs inside each other"],
  },
  {
    id: "button-group",
    name: "ButtonGroup",
    storyTitle: "Components/ButtonGroup",
    overview:
      "Segmented control for single or multi select. Selected items use yellow selected tokens (wayfinding), not primary button chrome.",
    whenToUse: ["View switchers", "Compact mutually exclusive or multi options"],
    variants: {
      size: ["sm", "md", "lg"],
      type: ["single", "multiple"],
      state: ["default", "hover", "disabled"],
    },
    anatomy: ["Group root", "Item(s)", "Optional icon"],
    tokens: {
      role: [
        "selected/bg",
        "selected/text",
        "text/primary",
        "border/subtle",
        "bg/surface",
        "border/focus",
      ],
      surface: ["surface/level-1"],
      structure: ["control/padding-x", "control/padding-y", "control/gap", "icon/size", "focus/ring-width"],
      component: ["segment/radius-outer", "segment/radius-inner"],
    },
    props: [
      { name: "type", type: "single | multiple", default: "single", description: "Selection mode." },
      { name: "size", type: "sm | md | lg", default: "md", description: "Item size." },
    ],
    accessibility: ["toggle group / toggle roles from Radix", "Selected state exposed to AT"],
    do: ["Use selected yellow for the active segment"],
    dont: ["Don't style selected segments as primary black buttons"],
  },
  {
    id: "dropdown",
    name: "Dropdown",
    storyTitle: "Components/Dropdown",
    overview:
      "Select (form value) and Menu (actions) built on Radix. Menus/select content use surface-raised + dropdown component tokens.",
    whenToUse: ["Select for choosing a value in a form", "Menu for action lists, including multi checkbox items"],
    variants: {
      kind: ["select", "menu"],
      state: ["default", "closed", "open", "item-hover", "item-selected", "item-disabled"],
    },
    anatomy: ["Trigger", "Content / viewport", "Item", "Separator / group / label"],
    tokens: {
      role: [
        "text/primary",
        "text/secondary",
        "text/disabled",
        "border/default",
        "border/subtle",
        "border/focus",
        "bg/surface-raised",
        "selected/field-hover",
      ],
      surface: ["surface/field", "surface/level-1", "surface/level-2"],
      structure: ["control/radius", "control/padding-x", "control/padding-y", "shadow/sm", "focus/ring-width"],
      component: [
        "dropdown/menu-radius",
        "dropdown/menu-padding-y",
        "dropdown/item-padding-x",
        "dropdown/item-padding-y",
      ],
      overlay: ["overlay/scrim"],
    },
    props: [
      { name: "Select.value", type: "string", description: "Controlled select value." },
      { name: "state", type: "design-review states", default: "default", description: "Design-review only." },
    ],
    accessibility: ["Combobox/listbox patterns from Radix Select", "Menu uses menu/menuitem roles", "Typeahead supported by Radix"],
    do: ["Use Select for values; Menu for commands", "Group long lists"],
    dont: ["Don't put destructive navigation behind an unlabeled icon-only trigger"],
  },
  {
    id: "progress",
    name: "Progress",
    storyTitle: "Components/Progress",
    overview: "Determinate or indeterminate progress bar with role colour on the indicator.",
    whenToUse: ["Upload/download progress", "Step completion", "Indeterminate loading when duration is unknown"],
    variants: {
      variant: ["neutral", "success", "danger"],
      mode: ["determinate", "indeterminate"],
      state: ["default"],
    },
    anatomy: ["Root", "Track", "Indicator", "Optional label / value"],
    tokens: {
      role: ["bg/neutral/strong", "bg/success/strong", "bg/danger/strong", "text/primary", "text/secondary"],
      component: ["progress/track-height", "progress/radius", "progress/label-gap", "progress/track-bg"],
    },
    props: [
      { name: "variant", type: "neutral | success | danger", default: "neutral", description: "Indicator colour." },
      { name: "value", type: "number | null", description: "0–100; null = indeterminate." },
      { name: "label", type: "string", description: "Visible label." },
      { name: "showValue", type: "boolean", default: "false", description: "Show numeric value." },
    ],
    accessibility: ["progressbar role", "aria-valuenow when determinate", "Indeterminate omits valuemin/max as appropriate"],
    do: ["Prefer determinate when you know progress", "Respect reduced motion on indeterminate"],
    dont: ["Don't use danger variant for ordinary loading"],
  },
  {
    id: "slider",
    name: "Slider",
    storyTitle: "Components/Slider",
    overview: "Single or range slider (Radix). Thumb uses Structure/component sizing; track uses surface/control.",
    whenToUse: ["Numeric ranges", "Opacity/volume style continuous input"],
    variants: {
      mode: ["single", "range"],
      state: ["default", "hover", "dragging", "disabled"],
    },
    anatomy: ["Root", "Track", "Range", "Thumb(s)", "Optional label"],
    tokens: {
      role: ["bg/neutral/strong", "bg/surface", "border/strong", "border/focus", "text/primary", "text/secondary"],
      component: ["slider/thumb-size", "slider/thumb-border", "slider/track-bg"],
      structure: ["focus/ring-width", "focus/ring-offset"],
    },
    props: [
      { name: "value", type: "number | [number, number]", description: "Single or range value." },
      { name: "state", type: "default | hover | dragging | disabled", default: "default", description: "Design-review only." },
    ],
    accessibility: ["slider role", "Arrow keys adjust value", "Thumbs are keyboard focusable"],
    do: ["Provide a text field nearby for precise entry when needed"],
    dont: ["Don't use Slider for binary on/off — use Toggle"],
  },
  {
    id: "card",
    name: "Card",
    storyTitle: "Components/Card",
    overview:
      "Surface container that sets data-context so nested cards resolve levels correctly. Default/interactive → surface; raised → surface-raised.",
    whenToUse: ["Grouping related content", "Nested panels", "Interactive selectable tiles (interactive variant)"],
    variants: {
      variant: ["default", "raised", "interactive"],
      state: ["default", "hover", "active", "focused", "disabled"],
    },
    anatomy: ["Root", "Optional header", "Body", "Optional footer"],
    tokens: {
      role: ["bg/surface", "bg/surface-raised", "text/primary", "text/secondary", "border/subtle", "border/focus"],
      surface: ["surface/level-1", "surface/level-2"],
      structure: ["shadow/sm", "layout/stack", "layout/stack-tight", "focus/ring-width"],
      component: ["card/radius", "card/padding"],
    },
    props: [
      { name: "variant", type: "default | raised | interactive", default: "default", description: "Elevation / interactivity." },
      { name: "header", type: "ReactNode", description: "Header slot." },
      { name: "footer", type: "ReactNode", description: "Footer slot." },
      { name: "state", type: "design-review states", default: "default", description: "Design-review only (interactive)." },
    ],
    accessibility: ["interactive cards need a clear accessible name and keyboard activation when used as buttons via asChild"],
    do: ["Nest default → raised to climb context", "Verify nested levels in light and dark"],
    dont: ["Don't hard-code context colours — let data-context resolve Surface tokens"],
  },
  {
    id: "alert",
    name: "Alert",
    storyTitle: "Components/Alert",
    overview:
      "Inline status message. Optional actions are always ghost Dismiss + secondary primary-action, coloured by the Alert role (danger → destructive).",
    whenToUse: ["Inline feedback", "Non-blocking warnings", "AI suggestions"],
    variants: {
      role: ["info", "success", "warning", "danger", "ai"],
      emphasis: ["soft", "strong"],
      state: ["default"],
    },
    anatomy: ["Root", "Title", "Body", "Actions (Dismiss + primary)"],
    tokens: {
      role: [
        "bg/info/soft",
        "bg/info/strong",
        "bg/success/soft",
        "bg/success/strong",
        "bg/warning/soft",
        "bg/warning/strong",
        "bg/danger/soft",
        "bg/danger/strong",
        "bg/ai/soft",
        "bg/ai/strong",
        "text/info",
        "text/success",
        "text/warning",
        "text/danger",
        "text/ai",
        "text/on-strong",
        "text/on-strong-warning",
        "border/info",
        "border/success",
        "border/warning",
        "border/danger",
        "border/ai",
      ],
      structure: ["layout/stack", "layout/stack-tight"],
      component: ["alert/radius", "alert/padding", "alert/icon-gap"],
    },
    props: [
      { name: "role", type: "info | success | warning | danger | ai", description: "Status colour." },
      { name: "emphasis", type: "soft | strong", default: "soft", description: "Fill weight." },
      { name: "actions", type: "{ primaryLabel, onPrimary?, onDismiss? }", description: "Standard action pair." },
      { name: "dismissible", type: "boolean", default: "false", description: "Ghost Dismiss only." },
    ],
    accessibility: ["role=status for live updates", "Actions are real Buttons"],
    do: ["Inherit Alert role onto action Button colours", "Use soft for most inline alerts"],
    dont: ["Never put a primary default button inside a coloured alert"],
  },
  {
    id: "modal",
    name: "Modal",
    storyTitle: "Components/Modal",
    overview:
      "Dialog with Overlay scrim and z/modal stacking. Panel is surface-raised so nested Cards resolve correctly.",
    whenToUse: ["Confirmations", "Focused forms", "Destructive confirms"],
    variants: {
      size: ["sm", "md", "lg"],
      state: ["default"],
    },
    anatomy: ["Trigger", "Overlay (scrim)", "Content panel", "Title", "Description", "Body", "Footer", "Close"],
    tokens: {
      role: [
        "bg/surface-raised",
        "text/primary",
        "text/secondary",
        "border/subtle",
        "border/focus",
        "icon/secondary",
        "icon/primary",
      ],
      surface: ["surface/level-1"],
      structure: ["shadow/sm", "layout/stack", "layout/stack-tight", "z/modal", "focus/ring-width"],
      overlay: ["overlay/scrim", "overlay/scrim-opacity"],
      component: [
        "modal/radius",
        "modal/padding",
        "modal/max-width-sm",
        "modal/max-width",
        "modal/max-width-lg",
      ],
    },
    props: [
      { name: "size", type: "sm | md | lg", default: "md", description: "Max width token." },
      { name: "title", type: "string", description: "Dialog title (required)." },
      { name: "open", type: "boolean", description: "Controlled open state." },
      { name: "trigger", type: "ReactNode", description: "Element that opens the dialog." },
      { name: "footer", type: "ReactNode", description: "Action row." },
    ],
    accessibility: [
      "dialog role from Radix",
      "Focus trapped while open",
      "Escape closes",
      "Title required for accessible name",
    ],
    do: ["Put destructive confirms in the footer with primary destructive", "Nest Card inside for complex content"],
    dont: ["Don't skip the title", "Don't use Modal for non-blocking inline messages — use Alert"],
  },
];

export function getComponentSpec(id: string): ComponentSpec | undefined {
  return COMPONENT_SPECS.find((s) => s.id === id);
}

export const COMPONENT_SPEC_IDS = COMPONENT_SPECS.map((s) => s.id);
