/**
 * Generates public/specs/* from the component registry + compiled tokens (spec §5).
 * Run: node --experimental-strip-types scripts/generate-specs.ts
 */
import {
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
  rmSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { COMPONENT_SPECS } from "../src/docs/component-specs/registry.ts";
import type { ComponentSpec } from "../src/docs/component-specs/types.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "public/specs");
const tokensCssDir = join(root, "src/styles/tokens");
const catalogPath = join(tokensCssDir, "tokens.json");

function pathToCssVar(tokenPath: string): string {
  return `--${tokenPath.replace(/\//g, "-")}`;
}

function toMarkdown(spec: ComponentSpec): string {
  const lines: string[] = [
    `# ${spec.name}`,
    "",
    spec.overview,
    "",
    "## When to use",
    "",
    ...spec.whenToUse.map((i) => `- ${i}`),
    "",
    "## Variant / state matrix",
    "",
  ];

  for (const [axis, values] of Object.entries(spec.variants)) {
    lines.push(`- **${axis}:** ${values.join(" | ")}`);
  }

  lines.push(
    "",
    "> `state` is a design-review affordance — leave at `default` in production.",
    "",
    "## Anatomy",
    "",
    ...spec.anatomy.map((p, i) => `${i + 1}. ${p}`),
    "",
    "## Tokens consumed",
    "",
  );

  for (const [layer, tokens] of Object.entries(spec.tokens)) {
    if (!tokens?.length) continue;
    lines.push(`### ${layer}`, "");
    for (const t of tokens) {
      lines.push(`- \`${t}\` → \`${pathToCssVar(t)}\``);
    }
    lines.push("");
  }

  lines.push("## Props", "");
  lines.push("| Prop | Type | Default | Description |");
  lines.push("| --- | --- | --- | --- |");
  for (const p of spec.props) {
    lines.push(
      `| \`${p.name}\` | ${p.type.replace(/\|/g, "\\|")} | ${p.default ?? "—"} | ${p.description} |`,
    );
  }

  lines.push("", "## Accessibility", "");
  lines.push(...spec.accessibility.map((i) => `- ${i}`));
  lines.push("", "## Do", "");
  lines.push(...spec.do.map((i) => `- ${i}`));
  lines.push("", "## Don't", "");
  lines.push(...spec.dont.map((i) => `- ${i}`));
  lines.push("");

  return lines.join("\n");
}

function toJson(spec: ComponentSpec) {
  return {
    id: spec.id,
    name: spec.name,
    storyTitle: spec.storyTitle,
    overview: spec.overview,
    whenToUse: spec.whenToUse,
    variants: spec.variants,
    anatomy: spec.anatomy,
    tokens: Object.fromEntries(
      Object.entries(spec.tokens).map(([layer, list]) => [
        layer,
        (list ?? []).map((path) => ({
          path,
          cssVar: pathToCssVar(path),
        })),
      ]),
    ),
    props: spec.props,
    accessibility: spec.accessibility,
    do: spec.do,
    dont: spec.dont,
  };
}

function buildFigmaVariables(catalog: {
  tokens: {
    name: string;
    cssVar: string;
    type: string;
    description: string;
    value: string | number | null;
    valueByMode: { light?: string | number; dark?: string | number } | null;
    path: string[];
  }[];
}) {
  return {
    $schema: "https://wingify.local/variant-ds/figma-variables-import",
    generated: true,
    note: "Import-shaped export for Figma variables tooling. Colour modes: light / dark when present.",
    variables: catalog.tokens.map((t) => {
      const valuesByMode: Record<string, string | number> = {};
      if (t.valueByMode?.light != null) valuesByMode.light = t.valueByMode.light;
      if (t.valueByMode?.dark != null) valuesByMode.dark = t.valueByMode.dark;
      if (Object.keys(valuesByMode).length === 0 && t.value != null) {
        valuesByMode.default = t.value;
      }
      return {
        name: t.path.join("/"),
        cssVar: t.cssVar,
        resolvedType:
          t.type === "color"
            ? "COLOR"
            : t.type === "dimension" || t.type === "number"
              ? "FLOAT"
              : "STRING",
        description: t.description,
        valuesByMode,
      };
    }),
  };
}

function concatTokenCss(): string {
  const files = [
    "primitive.css",
    "role.css",
    "surface.css",
    "structure.css",
    "overlay.css",
    "component.css",
  ];
  const parts = [
    "/** Generated by scripts/generate-specs.ts — full token CSS bundle. */\n",
  ];
  for (const file of files) {
    const abs = join(tokensCssDir, file);
    parts.push(`\n/* ===== ${file} ===== */\n`);
    parts.push(readFileSync(abs, "utf8"));
  }
  return parts.join("");
}

mkdirSync(outDir, { recursive: true });

// Clear previous generated files but keep .gitkeep
for (const name of readdirSync(outDir)) {
  if (name === ".gitkeep") continue;
  rmSync(join(outDir, name), { force: true, recursive: true });
}

const index: { id: string; name: string; files: string[] }[] = [];

for (const spec of COMPONENT_SPECS) {
  const mdName = `${spec.id}.md`;
  const jsonName = `${spec.id}.json`;
  writeFileSync(join(outDir, mdName), toMarkdown(spec), "utf8");
  writeFileSync(
    join(outDir, jsonName),
    `${JSON.stringify(toJson(spec), null, 2)}\n`,
    "utf8",
  );
  index.push({ id: spec.id, name: spec.name, files: [mdName, jsonName] });
}

const catalog = JSON.parse(readFileSync(catalogPath, "utf8"));
writeFileSync(
  join(outDir, "tokens.json"),
  `${JSON.stringify(catalog, null, 2)}\n`,
  "utf8",
);
writeFileSync(join(outDir, "tokens.css"), concatTokenCss(), "utf8");
writeFileSync(
  join(outDir, "tokens.figma.json"),
  `${JSON.stringify(buildFigmaVariables(catalog), null, 2)}\n`,
  "utf8",
);
writeFileSync(
  join(outDir, "index.json"),
  `${JSON.stringify(
    {
      generated: true,
      components: index,
      tokens: ["tokens.css", "tokens.json", "tokens.figma.json"],
    },
    null,
    2,
  )}\n`,
  "utf8",
);

console.log(
  `specs:build OK → ${outDir} (${COMPONENT_SPECS.length} components + token bundle)`,
);
